apiVersion: v1                         ## k8s 版本號
kind: Pod                              ## 服務類型
metadata:
  name: first-pod                      ## Pod 的名稱
spec:
  containers:
  - name: first-container              ## container 的名稱
    image: nginx                       ## 映像檔位置
    ports:                             ## 暴露 port 給其他資源存取
      - containerPort: 80